// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jakuxkviarwynyckvkhp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impha3V4a3ZpYXJ3eW55Y2t2a2hwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2NTg0NjEsImV4cCI6MjA3NDIzNDQ2MX0.NlNcTXe6wbuIcpaH7CtswMcqMmN4IhTaY-k9LOYayrA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});